### ISSUE TITLE
无法使用fastboot boot指令从固件启动

### ISSUE THREAD

**Issue by collins7184** [D8100-9000-TWRP-Device-Tree/device_xiaomi_rubens-TWRP#6]
以下是powershell信息：
PS C:\Users\colli\Desktop\TOOLS_BY_CZ_V7.52> .\fastboot.exe boot K50-vendor_boot-5.10.66-twrp-12.1-dev-20220622-1.img
creating boot image...
creating boot image - 67110912 bytes
Sending 'boot.img' (65538 KB)                      OKAY [  1.519s]
Booting                                            FAILED (remote: 'unknown command')
fastboot: error: Command failed

**Comment by YuKongA** [comment]
是的，这 就是联发科。联发科不能fastboot boot

**Comment by YuKongA** [comment]
是的，这 就是联发科。联发科不能fastboot boot。参考https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/2356#issue-1089040629

**Comment by railjty** [comment]
联发科设备完全不支持fastboot boot
请直接刷入vendor_boot_ab

**Comment by collins7184** [comment]
😂
